Parse build-args for empty values
ansible/ansible-builder pull request #517
Opened 2023-05-03 19:21 UTC by Akasurde

* Split for first equal sign in build-args
* Honor empty values in build-args

Fixes: #514

2023-05-04 17:25 UTC, nitzmahone requested changes

2023-05-04 17:25 UTC, nitzmahone commented on src/ansible_builder/main.py
> +            if value == '':
This logic should be wrapped up inside the `BuildArgAction` below, and probably just use `partition` to split the string- if the last element has no value but the second element is `=`, you know you need to tack an `=` onto the end of the key.

Also, as a general rule, embedding empty quotes in something that's going to get round-tripped to another CLI is probably going to cause a lot more problems than it solves; just having a trailing `=` on the arg should be sufficient in this case.

2023-05-04 17:25 UTC, nitzmahone commented on test/integration/test_build.py
> +@pytest.mark.test_all_runtimes
We can probably cover this adequately with decent unit tests on either the CLI parser or maybe even just the `BuildArgsAction` itself- another dedicated integration test is incredibly expensive for this case.

2023-05-04 17:29 UTC, nitzmahone commented
Can also probably fix #520 easily in this same PR while you're "in the neighborhood" :wink:

2023-05-05 18:24 UTC, nitzmahone commented on src/ansible_builder/main.py
> +            if value == '':
On further reflection, the placement here is fine, but we definitely don't want the `''` in the final command for that case (just `{key}=`). The logic should probably be more explicit though, as the YAML layer *could* technically provide an integer `0` value (the JSON schema might currently prevent it, but I don't know for sure), which would erroneously trigger the `else`. 

So probably just to be super safe have `BuildArgAction` provide a value of `None` for eg `--build-arg FOO`, `''` for `--build-arg FOO=` and of course the real value for anything else... Then the logic here should explicitly check for value being `None` and `''`, then the unqualified `else` case is the `{key}={value}` one.

2023-05-05 18:37 UTC, nitzmahone approved these changes

2023-05-05 19:03 UTC, Shrews approved these changes

2023-05-05 19:04 UTC, merged