[RFE] Support for tags from the configuration file
ansible/ansible-builder pull request #555
Opened 2023-06-05 20:11 UTC by Akasurde

##### SUMMARY

* Added support for providing tags from the configuration file

Fixes: #523

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

- Feature Pull Request
- Test Pull Request##### COMPONENT NAME
demo/execution-environment.yml
docs/definition.rst
src/ansible_builder/ee_schema.py
src/ansible_builder/main.py
test/unit/test_user_definition.py

2023-06-06 15:08 UTC, Shrews requested changes
We should probably test and account for a user specifying tags in both the EE file and on the command line. Not sure of the proper way to handle that case... combine the tags? ... prefer CLI over EE (similar to `--build-arg` CLI flag)?

2023-06-06 15:08 UTC, Shrews commented on src/ansible_builder/ee_schema.py
> +                    "type": ["string", "array", "null"],
Why allow `null`? I'd rather we only accept `array` here so we don't have to do code gymnastics to determine if it's a string or a list in other parts of the code.

2023-06-06 15:08 UTC, Shrews commented on src/ansible_builder/ee_schema.py
> +            "description": "Options that affects the runtime behavior",
```suggestion
            "description": "Options that affect the runtime behavior",
```

2023-06-06 18:29 UTC, Akasurde commented on src/ansible_builder/ee_schema.py
> +                    "type": ["string", "array", "null"],
Ok.

2023-06-06 18:32 UTC, Akasurde commented
> We should probably test and account for a user specifying tags in both the EE file and on the command line. Not sure of the proper way to handle that case... combine the tags? ... prefer CLI over EE (similar to `--build-arg` CLI flag)?

Right now I am combining the tags, if the user provided tags on both cli and ee def files.

2023-06-08 15:53 UTC, nitzmahone commented
CLI should override, not combine- that could cause unexpected behavior... The in-definition tags should only be a default if nothing else is provided.

2023-06-13 15:49 UTC, Shrews requested changes
Suggested some modifications to the schema to make it more robust.

Also, I tested this locally and the CLI `-t` option is not overriding the tags listed in the EE.

2023-06-13 15:49 UTC, Shrews commented on src/ansible_builder/ee_schema.py
> +                    "type": "array",
```suggestion
                    "type": "array",
                    "items": {
                        "type": "string"
                    }

```

2023-06-13 15:49 UTC, Shrews commented on src/ansible_builder/ee_schema.py
> +                    "description": "Specifies the name which is assigned to resulting image if build process completes successfully",
```suggestion
                    "description": "A list of names to assign to the resulting image if build process completes successfully",
```

2023-06-13 19:16 UTC, Shrews approved these changes

2023-06-13 23:09 UTC, merged